import test from 'node:test';
import assert from 'node:assert/strict';
import { contextIsAllowed, canReadEvidence, canSubmit, canReview } from '../.test-build/access.js';
import { submitReview, hrReview, reviseAssessment, canWriteToSource } from '../.test-build/review.js';
import { mapSkillObservation } from '../.test-build/orangehrm-mapping.js';
const manager = {tenantId:'a',actorId:'m',workspace:'manager'};
const hr = {tenantId:'a',actorId:'h',workspace:'hrbp'};
const member = {tenantId:'a',actorId:'m',workspaces:['personal','manager','hrbp'],directReportIds:['e'],clientGroupIds:['eng']};
const hmember = {...member,actorId:'h',directReportIds:[]};
const evidence = {id:'ev',tenantId:'a',subjectId:'e',groupId:'eng',source:'sample',observedAt:'2026-09-25',summary:'A work observation.',shared:true,current:true};
const review = {id:'r',tenantId:'a',subjectId:'e',subjectName:'Employee',groupId:'eng',managerId:'m',managerName:'Manager',hrReviewerId:'h',version:1,status:'draft',statement:'Specific assessment.',evidence:[evidence],reviewNote:''};
const submitted = () => submitReview(manager,member,review,1).review;
test('context must belong to the exact tenant and actor',()=>{assert.equal(contextIsAllowed(manager,member),true);assert.equal(contextIsAllowed({...manager,tenantId:'b'},member),false);assert.equal(contextIsAllowed({...manager,actorId:'h'},member),false)});
test('ungranted workspace is not available',()=>assert.equal(contextIsAllowed(hr,{...hmember,workspaces:['personal']}),false));
test('manager sees direct report evidence',()=>assert.equal(canReadEvidence(manager,member,evidence),true));
test('client group membership does not grant managerial access',()=>assert.equal(canReadEvidence(manager,{...member,directReportIds:[]},evidence),false));
test('private evidence is not exposed to HR',()=>assert.equal(canReadEvidence(hr,hmember,{...evidence,shared:false}),false));
test('personal mode cannot read another employee',()=>assert.equal(canReadEvidence({...manager,workspace:'personal'},member,evidence),false));
test('source evidence from another company is denied',()=>assert.equal(canReadEvidence(hr,hmember,{...evidence,tenantId:'b'}),false));
test('assigned manager submits and version increases',()=>{const x=submitted();assert.equal(x.status,'submitted');assert.equal(x.version,2)});
test('HR cannot submit a managers assessment',()=>assert.throws(()=>submitReview(hr,hmember,review,1),/assigned manager/));
test('stale submission version is rejected',()=>assert.throws(()=>submitReview(manager,member,review,0),/changed/));
test('submission needs current permitted evidence',()=>assert.throws(()=>submitReview(manager,member,{...review,evidence:[{...evidence,current:false}]},1),/current/));
test('manager cannot independently clear their own authored review',()=>assert.equal(canReview({...manager,workspace:'hrbp'},member,{...submitted(),hrReviewerId:'m'}),false));
test('employee cannot clear their own assessment',()=>assert.equal(canReview(hr,hmember,{...submitted(),subjectId:'h'}),false));
test('HR can request evidence without changing the assessment',()=>{const x=hrReview(hr,hmember,submitted(),2,'request_evidence','Which agreed obligation was missed?').review;assert.equal(x.status,'changes_requested');assert.equal(x.statement,review.statement)});
test('HR clearance is not finalization or a source write',()=>{const x=hrReview(hr,hmember,submitted(),2,'clear','The evidence question is resolved.').review;assert.equal(x.status,'hr_cleared');assert.equal(canWriteToSource(),false)});
test('HR needs a reason',()=>assert.throws(()=>hrReview(hr,hmember,submitted(),2,'clear',' '),/specific reason/));
test('new manager content invalidates old clearance',()=>{const cleared=hrReview(hr,hmember,submitted(),2,'clear','Resolved').review;const changed=reviseAssessment(manager,member,cleared,'Updated manager account.');assert.equal(changed.status,'draft');assert.equal(changed.version,3);assert.equal(changed.reviewNote,'')});
test('years of experience never become proficiency',()=>{const x=mapSkillObservation('a','instance1',{employeeId:'42',skillId:'9',yearsOfExperience:10,comments:'Self report'},'2026-09-25T09:00:00Z');assert.equal(x.proficiencyLevel,null);assert.equal(x.evidenceState,'unvalidated');assert.equal(x.assessorId,null)});
test('identical source IDs in different tenants remain different',()=>{const row={employeeId:'42',skillId:'9',yearsOfExperience:null,comments:''};const a=mapSkillObservation('a','source',row,'2026-09-25');const b=mapSkillObservation('b','source',row,'2026-09-25');assert.notEqual(a.contributorId,b.contributorId)});
test('invalid export values are rejected',()=>assert.throws(()=>mapSkillObservation('a','src',{employeeId:'42',skillId:'9',yearsOfExperience:-1,comments:''},'2026-09-25'),/non-negative/));
